config/routes.rb
FirstEdc::Application.routes.draw do

  # get "follow_up_log/index"

  # devise_for :users
  # resources :users do
  #   match '/permission', :to => 'users#permission', :via => [:get, :post]
  #   match '/users', :to => 'users#edit' , :via => [:get, :post]
  # end
  # resources :sessions, only: [:new, :create, :destroy]

  # match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  # # match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  # resources :baselines

  # match '/base_general_demo', :to => 'baselines#base_general_demo', :via => [:get, :post]
  # match '/baseline_view', :to => 'baselines#baseline_view', :via => [:get, :post]

  # resources :treatment_completions
  # match '/tc_view', :to => 'treatment_completions#tc_view', :via => [:get, :post]
  # resources :psychosocial_scales
  # resources :follow_up3_weeks
  # match '/fu3week_view', :to => 'follow_up3_weeks#fu3week_view', :via => [:get, :post]
  # resources :follow_up6_weeks
  # resources :follow_up18_weeks
  # match '/fu18week_view', :to => 'follow_up18_weeks#fu18week_view', :via => [:get, :post]
  # resources :follow_up6_months
  # match '/fu6month_view', :to => 'follow_up6_months#fu6month_view', :via => [:get, :post]
  # resources :follow_up1_years
  # match '/fu1year_view', :to => 'follow_up1_years#fu1year_view', :via => [:get, :post]
  
  # resources :data_queries

  # resources :follow_up_logs
  # match '/follow_up_log_site', :to => 'follow_up_logs#show', :via => [:get, :post]
  # match '/edit_follow_up_logs', :to => 'follow_up_logs#edit', :via => [:get, :post]

  # resources :subjects do
  #   match '/screening', :to => 'subjects#screening', :via => [:get, :post]
  #   match '/comment', :to => 'subjects#comment', :via => [:get, :post]
  # end

  # match '/screening_view', :to => 'subjects#screening_view', :via => [:get, :post]
  # match '/newsubject', :to => 'subjects#new', :via => [:get, :post]
  # match '/randomize', :to => 'subjects#randomize', :via => [:get, :post]
  # match '/screening_log', :to => 'subjects#screening_log', :via => [:get, :post]
  # match '/screening_crf_data', :to => 'subjects#screening_crf_data', :via => [:get, :post]
  # # resources :comments do
  # # end

  
  # devise_scope :user do
  #   root to: 'static_pages#home'
  #   match '/sessions/user', :to => 'devise/sessions#create', :via => [:get, :post]
  #   # match '/profile', to: 'users#show', via: :post
  #   match '/edit', :to => 'users#edit', :via => [:get, :post]
  # end  

  # match '/signup', :to => 'users#new', :via => [:get, :post]
  # match '/signin', :to => 'sessions#new', :via => [:get, :post]
  # match '/signout', :to => 'sessions#destroy', via: :delete
  

  # match '/help', :to => 'static_pages#help', :via => [:get, :post]
  # match '/about', :to => 'static_pages#about', :via => [:get, :post]
  # match '/contact', :to => 'static_pages#contact', :via => [:get, :post]


  get "follow_up_log/index"

#User Authentication



  devise_for :users
  resources :users do
    match '/permission', :to => 'users#permission', :via => [:get, :post]
    match '/users', :to => 'users#edit' , :via => [:get, :post]
  end

    # match '/sessions/signout', :to => 'devise/sessions#destroy', via: :delete
  devise_scope :user do
    root to: 'static_pages#home'
    match '/sessions/user', :to => 'devise/sessions#create', :via => [:get, :post]
    match '/edit', :to => 'users#edit', :via => [:get, :post]
  end  

  match '/signup', :to => 'users#new', :via => [:get, :post]
  match '/signin', :to => 'sessions#new', :via => [:get, :post]
  match '/signout', :to => 'sessions#destroy', via: :delete

  #Allow user to log in, carry on session
  resources :sessions, only: [:new, :create, :destroy]

#Statis Pages
  match '/help', :to => 'static_pages#help', :via => [:get, :post]
  match '/about', :to => 'static_pages#about', :via => [:get, :post]
  match '/contact', :to => 'static_pages#contact', :via => [:get, :post]


#CRF Routes
  resources :baselines
  match '/baseline_view', :to => 'baselines#baseline_view', :via => [:get, :post]
  match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  match '/base_general_demo', :to => 'baselines#base_general_demo', :via => [:get, :post]

  resources :follow_up3_weeks
  match '/fu3week_view', :to => 'follow_up3_weeks#fu3week_view', :via => [:get, :post]

  resources :treatment_completions
  match '/tc_view', :to => 'treatment_completions#tc_view', :via => [:get, :post]

  resources :follow_up18_weeks
  match '/fu18week_view', :to => 'follow_up18_weeks#fu18week_view', :via => [:get, :post]
  
  resources :follow_up6_months
  match '/fu6month_view', :to => 'follow_up6_months#fu6month_view', :via => [:get, :post]
  
  resources :psychosocial_scales
  
  #Route for a later feature, not yet implemented
  resources :follow_up1_years
  match '/fu1year_view', :to => 'follow_up1_years#fu1year_view', :via => [:get, :post]
  
  resources :data_queries

  resources :follow_up_logs
  match '/follow_up_log_site', :to => 'follow_up_logs#show', :via => [:get, :post]
  match '/edit_follow_up_logs', :to => 'follow_up_logs#edit', :via => [:get, :post]
  
#Subjects Routes
  resources :subjects do
    match '/screening', :to => 'subjects#screening', :via => [:get, :post]
    match '/comment', :to => 'subjects#comment', :via => [:get, :post]
  end

  match '/screening_view', :to => 'subjects#screening_view', :via => [:get, :post]
  match '/newsubject', :to => 'subjects#new', :via => [:get, :post]
  match '/randomize', :to => 'subjects#randomize', :via => [:get, :post]
  match '/screening_log', :to => 'subjects#screening_log', :via => [:get, :post]
  match '/screening_crf_data', :to => 'subjects#screening_crf_data', :via => [:get, :post]
end

app/models/data_query.rb
class DataQuery < ActiveRecord::Base
	# Deprecated
  # attr_accessible :data_manager, :subject_id, :investigator_name, :crf_measure_number, :query_notes, :resolution_notes
end

app/controllers/data_queries_controller.rb
class DataQueriesController < ApplicationController
	def index
		@data_queries = DataQuery.all
	end

	def show
		@data_query = DataQuery.find(params[:id])
	end

	def new
		@data_query = DataQuery.new
	end

	def create
		@data_query = DataQuery.new(params[:data_query])
		if @data_query.save
			flash[:success] = "Query created."
			redirect_to @data_query
		else
			render 'new'
		end
	end

	def update
		@data_query = DataQuery.find(params[:id])
		if @data_query.update_attributes(params[:data_query])
			flash[:success] = "Query updated."
		else
			render 'edit'
		end
	end

	def edit
		@data_query = DataQuery.find(params[:id])
	end

	def destroy
		if current_user.is? :admin
		  @data_query = DataQuery.find(params[:id])
		  @data_query.destroy

		  respond_to do |format|
		    format.html { redirect_to @data_query }
		    format.json { head :no_content }
		  end
		end
	end

private
	def data_query_params
		params.require(:data_query).permit(:data_manager, :subject_id, :investigator_name, :crf_measure_number, :query_notes, :resolution_notes)
	end

end

app/helpers/data_queries_helper.rb
module DataQueriesHelper
end

app/views/data_queries/edit.html.erb
<% provide(:title, 'Edit Data Query') %>
<h1>Add a Data Query</h1>

<div class="row">
	<div class="span6 offset3">
		<div style="width:300px;margin:auto;">
			<%= form_for :data_query, url: data_queries_path do |f| %>
				<p>Subject ID:</p>
				<%= f.number_field :subject_id %>
				<p>Data Manager:</p>
				<%= f.text_field :data_manager %>
				<p>CRF, Measure, and item number:</p>
				<%= f.text_field :crf_measure_number %>
				<p>Query notes:</p>
				<%= f.text_field :query_notes %>
				<p>Investigator:</p>
				<%= f.text_field :investigator_name %>
				<p>Resolution notes:</p>
				<%= f.text_field :resolution_notes %>
				
				<%= f.submit "Update Data Query", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/data_queries/index.html.erb
<h1>Data Query Log</h1>
<table style="margin:auto" class="table table-hover">
	<tr>
		<th>Subject ID</th>
		<th>Data Manager</th>
		<th>CRF,Measure,Number</th>
		<th>Query Notes</th>
		<th>Investigator</th>
		<th>Resolution Notes</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<% @data_queries.each do |query| %>
		<tr>
			<td><%= query.subject_id %></td>
			<td><%= query.data_manager %></td>
			<td><%= query.crf_measure_number %></td>
			<td><%= query.query_notes %></td>
			<td><%= query.investigator_name %></td>
			<td><%= query.resolution_notes %></td>
			<td><%= link_to "Edit", edit_data_query_path(query.id) %></td>
			<td><%= link_to "Delete", query, method: :delete, confirm: "Delete subject?" %></td>
		</tr>
	<% end %>
</table>

<%= link_to "New Query", new_data_query_path %>

app/views/data_queries/new.html.erb
<% provide(:title, 'Add Data Query') %>
<h1>Add a Data Query</h1>

<div class="row">
	<div class="span6 offset3">
		<div style="width:300px;margin:auto;">
			<%= form_for :data_query, url: data_queries_path do |f| %>
				<p>Subject ID:</p>
				<%= f.number_field :subject_id %>
				<p>Data Manager:</p>
				<%= f.text_field :data_manager %>
				<p>CRF, Measure, and item number:</p>
				<%= f.text_field :crf_measure_number %>
				<p>Query notes:</p>
				<%= f.text_field :query_notes %>
				<p>Investigator:</p>
				<%= f.text_field :investigator_name %>
				<p>Resolution notes:</p>
				<%= f.text_field :resolution_notes %>
				
				<%= f.submit "Create Data Query", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/data_queries/show.html.erb
<%= link_to "Return to Data Query Log", data_queries_path %>