config/routes.rb
FirstEdc::Application.routes.draw do

  # get "follow_up_log/index"

  # devise_for :users
  # resources :users do
  #   match '/permission', :to => 'users#permission', :via => [:get, :post]
  #   match '/users', :to => 'users#edit' , :via => [:get, :post]
  # end
  # resources :sessions, only: [:new, :create, :destroy]

  # match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  # # match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  # resources :baselines

  # match '/base_general_demo', :to => 'baselines#base_general_demo', :via => [:get, :post]
  # match '/baseline_view', :to => 'baselines#baseline_view', :via => [:get, :post]

  # resources :treatment_completions
  # match '/tc_view', :to => 'treatment_completions#tc_view', :via => [:get, :post]
  # resources :psychosocial_scales
  # resources :follow_up3_weeks
  # match '/fu3week_view', :to => 'follow_up3_weeks#fu3week_view', :via => [:get, :post]
  # resources :follow_up6_weeks
  # resources :follow_up18_weeks
  # match '/fu18week_view', :to => 'follow_up18_weeks#fu18week_view', :via => [:get, :post]
  # resources :follow_up6_months
  # match '/fu6month_view', :to => 'follow_up6_months#fu6month_view', :via => [:get, :post]
  # resources :follow_up1_years
  # match '/fu1year_view', :to => 'follow_up1_years#fu1year_view', :via => [:get, :post]
  
  # resources :data_queries

  # resources :follow_up_logs
  # match '/follow_up_log_site', :to => 'follow_up_logs#show', :via => [:get, :post]
  # match '/edit_follow_up_logs', :to => 'follow_up_logs#edit', :via => [:get, :post]

  # resources :subjects do
  #   match '/screening', :to => 'subjects#screening', :via => [:get, :post]
  #   match '/comment', :to => 'subjects#comment', :via => [:get, :post]
  # end

  # match '/screening_view', :to => 'subjects#screening_view', :via => [:get, :post]
  # match '/newsubject', :to => 'subjects#new', :via => [:get, :post]
  # match '/randomize', :to => 'subjects#randomize', :via => [:get, :post]
  # match '/screening_log', :to => 'subjects#screening_log', :via => [:get, :post]
  # match '/screening_crf_data', :to => 'subjects#screening_crf_data', :via => [:get, :post]
  # # resources :comments do
  # # end

  
  # devise_scope :user do
  #   root to: 'static_pages#home'
  #   match '/sessions/user', :to => 'devise/sessions#create', :via => [:get, :post]
  #   # match '/profile', to: 'users#show', via: :post
  #   match '/edit', :to => 'users#edit', :via => [:get, :post]
  # end  

  # match '/signup', :to => 'users#new', :via => [:get, :post]
  # match '/signin', :to => 'sessions#new', :via => [:get, :post]
  # match '/signout', :to => 'sessions#destroy', via: :delete
  

  # match '/help', :to => 'static_pages#help', :via => [:get, :post]
  # match '/about', :to => 'static_pages#about', :via => [:get, :post]
  # match '/contact', :to => 'static_pages#contact', :via => [:get, :post]


  get "follow_up_log/index"

#User Authentication



  devise_for :users
  resources :users do
    match '/permission', :to => 'users#permission', :via => [:get, :post]
    match '/users', :to => 'users#edit' , :via => [:get, :post]
  end

    # match '/sessions/signout', :to => 'devise/sessions#destroy', via: :delete
  devise_scope :user do
    root to: 'static_pages#home'
    match '/sessions/user', :to => 'devise/sessions#create', :via => [:get, :post]
    match '/edit', :to => 'users#edit', :via => [:get, :post]
  end  

  match '/signup', :to => 'users#new', :via => [:get, :post]
  match '/signin', :to => 'sessions#new', :via => [:get, :post]
  match '/signout', :to => 'sessions#destroy', via: :delete

  #Allow user to log in, carry on session
  resources :sessions, only: [:new, :create, :destroy]

#Statis Pages
  match '/help', :to => 'static_pages#help', :via => [:get, :post]
  match '/about', :to => 'static_pages#about', :via => [:get, :post]
  match '/contact', :to => 'static_pages#contact', :via => [:get, :post]


#CRF Routes
  resources :baselines
  match '/baseline_view', :to => 'baselines#baseline_view', :via => [:get, :post]
  match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  match '/base_general_demo', :to => 'baselines#base_general_demo', :via => [:get, :post]

  resources :follow_up3_weeks
  match '/fu3week_view', :to => 'follow_up3_weeks#fu3week_view', :via => [:get, :post]

  resources :treatment_completions
  match '/tc_view', :to => 'treatment_completions#tc_view', :via => [:get, :post]

  resources :follow_up18_weeks
  match '/fu18week_view', :to => 'follow_up18_weeks#fu18week_view', :via => [:get, :post]
  
  resources :follow_up6_months
  match '/fu6month_view', :to => 'follow_up6_months#fu6month_view', :via => [:get, :post]
  
  resources :psychosocial_scales
  
  #Route for a later feature, not yet implemented
  resources :follow_up1_years
  match '/fu1year_view', :to => 'follow_up1_years#fu1year_view', :via => [:get, :post]
  
  resources :data_queries

  resources :follow_up_logs
  match '/follow_up_log_site', :to => 'follow_up_logs#show', :via => [:get, :post]
  match '/edit_follow_up_logs', :to => 'follow_up_logs#edit', :via => [:get, :post]
  
#Subjects Routes
  resources :subjects do
    match '/screening', :to => 'subjects#screening', :via => [:get, :post]
    match '/comment', :to => 'subjects#comment', :via => [:get, :post]
  end

  match '/screening_view', :to => 'subjects#screening_view', :via => [:get, :post]
  match '/newsubject', :to => 'subjects#new', :via => [:get, :post]
  match '/randomize', :to => 'subjects#randomize', :via => [:get, :post]
  match '/screening_log', :to => 'subjects#screening_log', :via => [:get, :post]
  match '/screening_crf_data', :to => 'subjects#screening_crf_data', :via => [:get, :post]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<h1>About Us</h1>
<p>This page is a work in progress.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<center><p>This site is currently under development. If you need help with anything, you can contact the Data Manger, Ian Ellis, via email: ian@specri.com.</p></center>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<h1>Help</h1>

<div class="span6 offset3">
	<div>
		<center><p>This site is currently under development. If you need help with anything, you can contact the Data Manger, Ian Ellis, via email: ian@specri.com.</p></center>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="hero-unit">
	<h1>VetPALS EDC</h1>
	<h2>VetPALS Electronic Data Capture web platform</h2>

	<div id="homepage_body">
		<div id="homepage_text">
			<h3 class="center"><b>Welcome</b></h3>
			<% if signed_in? %>
				<p><strong>For a new screened participant:</strong></p>
				<ol>
					<li>Click on <i><%= link_to "Enter New Participant", newsubject_path %></i></li>
					<li>Follow the prompts to select Study Site and enter a screening number.</li>
				</ol>

				<p><strong>If you've already entered screening information, you can:</strong></p>
				<ol>
					<li>View the <%= link_to "screening log", screening_log_path %></li>
					<li>View the <%= link_to "participant log", subjects_path %></li>
					<li>Change incorrectly entered information by contacting <a href="mailto:ian@specri.com">Ian Ellis</a> </li>
					<li>Finally, you can view, edit, and update the <%= link_to "follow up log", follow_up_logs_path %>.</li>
				</ol>
			<% else %>
				<p>
					Please sign in to continue,
					or make a new account. New account will have to be verified by an admin before they
					become active.
				</p>
				<p>
					If you have any question about this site, or ideas to improve upon the site, 
					email me at <a href="mailto:ian@specri.com">Ian Ellis</a>.
				</p>
				<p>This site is under development, with new features being added daily.</p>
			<% end %>
		</div>
		<div id="homepage_links">
			<h3 class="center" id="homepage_titles"><b>Links</b></h3>
			<% if signed_in? %>
				<ul><li><%= link_to "Enter Participant", newsubject_path %></li></ul>
				<ul><li><%= link_to "View Screening Log", screening_log_path %></li></ul>
				<ul><li><%= link_to "View Participants", subjects_path %></li></ul>
				<ul><li><%= link_to "View Follow Up Log", follow_up_logs_path %></li></ul>
				<ul><li><%= link_to "View Data Query Log", data_queries_path %></li></ul>

			<% else %>
				<ul>
					<li><%= link_to "Create new account", signup_path, class: "btn" %></li>
					<li><%= link_to "Log in", signin_path, class: "btn" %></li>
				</ul>
			<% end %>
		</div>
		<div id="homepage_news">
			<h3 class="center" id="homepage_titles"><b>Information</b></h3>
			<ul type="circle">
				<li>Contact</li>
				<ul>
					<li><i>Ian's cell: 253-380-7936	</i></li>
					<li><i>ian@specri.com</i></li>
				</ul>
				<li>Troubleshooting</li>
				<ul>
					<li>Please let me know if you find any bugs!</li>
				</ul>

				
			</ul>
		</div>
		<div class="clear"></div>
	</div>
</div>


<!-- <%= link_to image_tag("rails.png", alt: "Spectrum Research"), 'http://specri.com' %> -->