config/routes.rb
FirstEdc::Application.routes.draw do

  # get "follow_up_log/index"

  # devise_for :users
  # resources :users do
  #   match '/permission', :to => 'users#permission', :via => [:get, :post]
  #   match '/users', :to => 'users#edit' , :via => [:get, :post]
  # end
  # resources :sessions, only: [:new, :create, :destroy]

  # match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  # # match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  # resources :baselines

  # match '/base_general_demo', :to => 'baselines#base_general_demo', :via => [:get, :post]
  # match '/baseline_view', :to => 'baselines#baseline_view', :via => [:get, :post]

  # resources :treatment_completions
  # match '/tc_view', :to => 'treatment_completions#tc_view', :via => [:get, :post]
  # resources :psychosocial_scales
  # resources :follow_up3_weeks
  # match '/fu3week_view', :to => 'follow_up3_weeks#fu3week_view', :via => [:get, :post]
  # resources :follow_up6_weeks
  # resources :follow_up18_weeks
  # match '/fu18week_view', :to => 'follow_up18_weeks#fu18week_view', :via => [:get, :post]
  # resources :follow_up6_months
  # match '/fu6month_view', :to => 'follow_up6_months#fu6month_view', :via => [:get, :post]
  # resources :follow_up1_years
  # match '/fu1year_view', :to => 'follow_up1_years#fu1year_view', :via => [:get, :post]
  
  # resources :data_queries

  # resources :follow_up_logs
  # match '/follow_up_log_site', :to => 'follow_up_logs#show', :via => [:get, :post]
  # match '/edit_follow_up_logs', :to => 'follow_up_logs#edit', :via => [:get, :post]

  # resources :subjects do
  #   match '/screening', :to => 'subjects#screening', :via => [:get, :post]
  #   match '/comment', :to => 'subjects#comment', :via => [:get, :post]
  # end

  # match '/screening_view', :to => 'subjects#screening_view', :via => [:get, :post]
  # match '/newsubject', :to => 'subjects#new', :via => [:get, :post]
  # match '/randomize', :to => 'subjects#randomize', :via => [:get, :post]
  # match '/screening_log', :to => 'subjects#screening_log', :via => [:get, :post]
  # match '/screening_crf_data', :to => 'subjects#screening_crf_data', :via => [:get, :post]
  # # resources :comments do
  # # end

  
  # devise_scope :user do
  #   root to: 'static_pages#home'
  #   match '/sessions/user', :to => 'devise/sessions#create', :via => [:get, :post]
  #   # match '/profile', to: 'users#show', via: :post
  #   match '/edit', :to => 'users#edit', :via => [:get, :post]
  # end  

  # match '/signup', :to => 'users#new', :via => [:get, :post]
  # match '/signin', :to => 'sessions#new', :via => [:get, :post]
  # match '/signout', :to => 'sessions#destroy', via: :delete
  

  # match '/help', :to => 'static_pages#help', :via => [:get, :post]
  # match '/about', :to => 'static_pages#about', :via => [:get, :post]
  # match '/contact', :to => 'static_pages#contact', :via => [:get, :post]


  get "follow_up_log/index"

#User Authentication



  devise_for :users
  resources :users do
    match '/permission', :to => 'users#permission', :via => [:get, :post]
    match '/users', :to => 'users#edit' , :via => [:get, :post]
  end

    # match '/sessions/signout', :to => 'devise/sessions#destroy', via: :delete
  devise_scope :user do
    root to: 'static_pages#home'
    match '/sessions/user', :to => 'devise/sessions#create', :via => [:get, :post]
    match '/edit', :to => 'users#edit', :via => [:get, :post]
  end  

  match '/signup', :to => 'users#new', :via => [:get, :post]
  match '/signin', :to => 'sessions#new', :via => [:get, :post]
  match '/signout', :to => 'sessions#destroy', via: :delete

  #Allow user to log in, carry on session
  resources :sessions, only: [:new, :create, :destroy]

#Statis Pages
  match '/help', :to => 'static_pages#help', :via => [:get, :post]
  match '/about', :to => 'static_pages#about', :via => [:get, :post]
  match '/contact', :to => 'static_pages#contact', :via => [:get, :post]


#CRF Routes
  resources :baselines
  match '/baseline_view', :to => 'baselines#baseline_view', :via => [:get, :post]
  match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  match '/base_general_demo', :to => 'baselines#base_general_demo', :via => [:get, :post]

  resources :follow_up3_weeks
  match '/fu3week_view', :to => 'follow_up3_weeks#fu3week_view', :via => [:get, :post]

  resources :treatment_completions
  match '/tc_view', :to => 'treatment_completions#tc_view', :via => [:get, :post]

  resources :follow_up18_weeks
  match '/fu18week_view', :to => 'follow_up18_weeks#fu18week_view', :via => [:get, :post]
  
  resources :follow_up6_months
  match '/fu6month_view', :to => 'follow_up6_months#fu6month_view', :via => [:get, :post]
  
  resources :psychosocial_scales
  
  #Route for a later feature, not yet implemented
  resources :follow_up1_years
  match '/fu1year_view', :to => 'follow_up1_years#fu1year_view', :via => [:get, :post]
  
  resources :data_queries

  resources :follow_up_logs
  match '/follow_up_log_site', :to => 'follow_up_logs#show', :via => [:get, :post]
  match '/edit_follow_up_logs', :to => 'follow_up_logs#edit', :via => [:get, :post]
  
#Subjects Routes
  resources :subjects do
    match '/screening', :to => 'subjects#screening', :via => [:get, :post]
    match '/comment', :to => 'subjects#comment', :via => [:get, :post]
  end

  match '/screening_view', :to => 'subjects#screening_view', :via => [:get, :post]
  match '/newsubject', :to => 'subjects#new', :via => [:get, :post]
  match '/randomize', :to => 'subjects#randomize', :via => [:get, :post]
  match '/screening_log', :to => 'subjects#screening_log', :via => [:get, :post]
  match '/screening_crf_data', :to => 'subjects#screening_crf_data', :via => [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # has_and_belongs_to_many :roles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # Deprecated
  # attr_accessible :roles, :user_study_site
  # attr_accessible :email, :password, :password_confirmation, :remember_me, :roles_mask
  # attr_accessible :name, :site_study_coordinator, :project_coordinator, :site_pi, :lead_pi_sc, :vetpals_facilitator, :other_site_investigators
  
  # attr_accessible :title, :body

  ####
  # Role Based Association 
  # https://github.com/ryanb/cancan/wiki/Role-Based-Authorization
  ####
  ROLES = %w[admin site_study_coordinator project_coordinator site_pi lead_pi_sc vetpals_facilitator other_site_investigators]
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def is?(role)
    roles.include?(role.to_s)
  end

  ####
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # load_and_authorize_resource

  def index
    @users = User.paginate(page: params[:page])
  end
 
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to your User Profile"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    # authorize! :assign_roles, @user if params[:user][:assign_roles]
    @user = User.find(params[:id])
  end

  def update
    authorize! :assign_roles, @user if params[:user][:assign_roles]
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      if params[:user][:assign_roles]
        flash[:success] = "User can assign roles"
      else
        flash[:success] = @user.name
      end
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User has been deleted."
    redirect_to users_path
  end

  def permission
    # raise User.where(params[:id]).inspect
    @user = User.find(params[:user_id])
  end

private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user_?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  # Add after updating, because attr_accessor has been deprecated
  def user_params
    params.require(:user).permit(:roles, :user_study_site, :email, :password, :password_confirmation, :remember_me, :roles_mask, :name, :site_study_coordinator, :project_coordinator, :site_pi, :lead_pi_sc, :vetpals_facilitator, :other_site_investigators)
    # params.require(:user).permit(:roles, :user_study_site, :email, :password, :password_confirmation, :remember_me, :roles_mask, :name, :site_study_coordinator, :project_coordinator, :site_pi, :lead_pi_sc, :vetpals_facilitator, :other_site_investigators)
  end
  

end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "http://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}.png"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/_admin_fields.erb
<div class="admin_fields">
	<h2>Admin Variables</h2>
		<b>Site Study Coordinator</b>
		<%= f.select :site_study_coordinator, ([['',nil], ['true', true], ['false', false]]), :include_blank => @user.site_study_coordinator %>
		<b>Project Coordinator</b>
		<%= f.select :project_coordinator, ([['',nil], ['true', true], ['false', false]]), :include_blank => @user.project_coordinator %>
		<b>Site PI</b>
		<%= f.select :site_pi, ([['',nil], ['true', true], ['false', false]]), :include_blank => @user.site_pi %>
		<b>Lead PI SC</b>
		<%= f.select :lead_pi_sc, ([['',nil], ['true', true], ['false', false]]), :include_blank => @user.lead_pi_sc %>
		<b>VetPALS Facilitator</b>
		<%= f.select :vetpals_facilitator, ([['',nil], ['true', true], ['false', false]]), :include_blank => @user.vetpals_facilitator %>
		<b>Other Site Investigators</b>
		<%= f.select :other_site_investigators, ([['',nil], ['true', true], ['false', false]]), :include_blank => @user.other_site_investigators %>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>
<h2>User Information</h2>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<% @users.each do |user| %>
	<li>
		<%= gravatar_for user, size: 52 %>
		<%= link_to user.name, user %>
		<% if can? :assign_roles, @user %>
			| <%= link_to "delete", user, method: :delete, confirm: "Delete user?" %>
			| <%= link_to "edit", edit_user_path(user) %>
			| <%= link_to "permission", user_permission_path(user) %>
		<% end %>
	</li>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

	<div class="row">
		<div class="span6 offset3" style="width:300px; margin:auto;">
			<%= form_for(@user) do |f| %>
				<%= render 'fields', f: f %>
				<% if current_user.is? :admin %>
					Place holder
				<% end %>
				<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
			<% end %>

			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails">change gravitar image</a>
		</div>
	</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
	<h1>All users</h1>

<%= will_paginate %>

	<ul class="users">
		<%= render 'user' %>
	</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<div style="width:300px;margin:auto;">
			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages' %>

				<%= f.label :name %>
				<%= f.text_field :name %>

				<%= f.label :email %>
				<%= f.text_field :email %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation %>
				
				<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/permission.html.erb
<% provide(:title, 'Permissions') %>
<h1>User Permissions</h1>

	<div class="row">
		<div class="span6 offset3" style="width:300px; margin:auto;">
			<%= form_for @user do |f| %>
				<% if current_user.is? :admin %>
					<% if can? :assign_roles, @user %>
						<% for role in User::ROLES %>
							<%= label_tag "user_roles_#{role}", role.humanize %>
							<%= check_box_tag "user[roles][#{role}]", role, @user.roles.include?(role), {:name => "user[roles][]"} %> 
						<% end %>
						<%= hidden_field_tag "user[roles][]", "" %>
					<% end %>
				<% end %>
				<%= f.select :user_study_site, [[' ', nil],["Seattle", 1],["Houston", 2],["Cleveland", 3],["Tampa", 4],["Minneapolis", 5]] %>

				<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
			<% end %>

			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails">change gravitar image</a>
		</div>
	</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
			<b><%= @user.user_study_site == 1? "Seattle" : @user.user_study_site == 2? "Houston" : @user.user_study_site == 3? "Cleveland" : @user.user_study_site == 4? "Tampa" : @user.user_study_site == 5? "Minneapolis" : "nil"%></b>
			<% @user.roles.each do |role| %>
				| <%= role.camelize %>
			<% end %>
			
			<hr>
		</section>
		<div class="user_profile">
			
			<h2UserProfile>Tools</h2UserProfile></br>
			
			Here you will find links to the various tasks you are allowed access to.
			<ol>
				<li><%= link_to "Add a new Participant", newsubject_path %></li>
				<li><%= link_to "View Screening Log", screening_log_path %></li>
				<li><%= link_to "View Participant", subjects_path %></li>
			</ol>

			<hr>
			<!-- Admin Stuff -->
			<% if current_user.is? :admin %>
				<h2UserProfile>Admin Tools</h2UserProfile>
				
				<p><%= link_to "Screening Data", screening_crf_data_path %></p>
				<p><%= link_to "Screening Data for Tables", screening_view_path%></p>
				<p><%= link_to "Race/Gender Distrubtion Tables", race_gender_table_path%></p>
				
			<% end %>
		</div>
	</aside>
</div>