config/routes.rb
FirstEdc::Application.routes.draw do

  # get "follow_up_log/index"

  # devise_for :users
  # resources :users do
  #   match '/permission', :to => 'users#permission', :via => [:get, :post]
  #   match '/users', :to => 'users#edit' , :via => [:get, :post]
  # end
  # resources :sessions, only: [:new, :create, :destroy]

  # match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  # # match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  # resources :baselines

  # match '/base_general_demo', :to => 'baselines#base_general_demo', :via => [:get, :post]
  # match '/baseline_view', :to => 'baselines#baseline_view', :via => [:get, :post]

  # resources :treatment_completions
  # match '/tc_view', :to => 'treatment_completions#tc_view', :via => [:get, :post]
  # resources :psychosocial_scales
  # resources :follow_up3_weeks
  # match '/fu3week_view', :to => 'follow_up3_weeks#fu3week_view', :via => [:get, :post]
  # resources :follow_up6_weeks
  # resources :follow_up18_weeks
  # match '/fu18week_view', :to => 'follow_up18_weeks#fu18week_view', :via => [:get, :post]
  # resources :follow_up6_months
  # match '/fu6month_view', :to => 'follow_up6_months#fu6month_view', :via => [:get, :post]
  # resources :follow_up1_years
  # match '/fu1year_view', :to => 'follow_up1_years#fu1year_view', :via => [:get, :post]
  
  # resources :data_queries

  # resources :follow_up_logs
  # match '/follow_up_log_site', :to => 'follow_up_logs#show', :via => [:get, :post]
  # match '/edit_follow_up_logs', :to => 'follow_up_logs#edit', :via => [:get, :post]

  # resources :subjects do
  #   match '/screening', :to => 'subjects#screening', :via => [:get, :post]
  #   match '/comment', :to => 'subjects#comment', :via => [:get, :post]
  # end

  # match '/screening_view', :to => 'subjects#screening_view', :via => [:get, :post]
  # match '/newsubject', :to => 'subjects#new', :via => [:get, :post]
  # match '/randomize', :to => 'subjects#randomize', :via => [:get, :post]
  # match '/screening_log', :to => 'subjects#screening_log', :via => [:get, :post]
  # match '/screening_crf_data', :to => 'subjects#screening_crf_data', :via => [:get, :post]
  # # resources :comments do
  # # end

  
  # devise_scope :user do
  #   root to: 'static_pages#home'
  #   match '/sessions/user', :to => 'devise/sessions#create', :via => [:get, :post]
  #   # match '/profile', to: 'users#show', via: :post
  #   match '/edit', :to => 'users#edit', :via => [:get, :post]
  # end  

  # match '/signup', :to => 'users#new', :via => [:get, :post]
  # match '/signin', :to => 'sessions#new', :via => [:get, :post]
  # match '/signout', :to => 'sessions#destroy', via: :delete
  

  # match '/help', :to => 'static_pages#help', :via => [:get, :post]
  # match '/about', :to => 'static_pages#about', :via => [:get, :post]
  # match '/contact', :to => 'static_pages#contact', :via => [:get, :post]


  get "follow_up_log/index"

#User Authentication



  devise_for :users
  resources :users do
    match '/permission', :to => 'users#permission', :via => [:get, :post]
    match '/users', :to => 'users#edit' , :via => [:get, :post]
  end

    # match '/sessions/signout', :to => 'devise/sessions#destroy', via: :delete
  devise_scope :user do
    root to: 'static_pages#home'
    match '/sessions/user', :to => 'devise/sessions#create', :via => [:get, :post]
    match '/edit', :to => 'users#edit', :via => [:get, :post]
  end  

  match '/signup', :to => 'users#new', :via => [:get, :post]
  match '/signin', :to => 'sessions#new', :via => [:get, :post]
  match '/signout', :to => 'sessions#destroy', via: :delete

  #Allow user to log in, carry on session
  resources :sessions, only: [:new, :create, :destroy]

#Statis Pages
  match '/help', :to => 'static_pages#help', :via => [:get, :post]
  match '/about', :to => 'static_pages#about', :via => [:get, :post]
  match '/contact', :to => 'static_pages#contact', :via => [:get, :post]


#CRF Routes
  resources :baselines
  match '/baseline_view', :to => 'baselines#baseline_view', :via => [:get, :post]
  match '/race_gender_table', :to => 'baselines#race_gender_table', :via => [:get, :post]
  match '/base_general_demo', :to => 'baselines#base_general_demo', :via => [:get, :post]

  resources :follow_up3_weeks
  match '/fu3week_view', :to => 'follow_up3_weeks#fu3week_view', :via => [:get, :post]

  resources :treatment_completions
  match '/tc_view', :to => 'treatment_completions#tc_view', :via => [:get, :post]

  resources :follow_up18_weeks
  match '/fu18week_view', :to => 'follow_up18_weeks#fu18week_view', :via => [:get, :post]
  
  resources :follow_up6_months
  match '/fu6month_view', :to => 'follow_up6_months#fu6month_view', :via => [:get, :post]
  
  resources :psychosocial_scales
  
  #Route for a later feature, not yet implemented
  resources :follow_up1_years
  match '/fu1year_view', :to => 'follow_up1_years#fu1year_view', :via => [:get, :post]
  
  resources :data_queries

  resources :follow_up_logs
  match '/follow_up_log_site', :to => 'follow_up_logs#show', :via => [:get, :post]
  match '/edit_follow_up_logs', :to => 'follow_up_logs#edit', :via => [:get, :post]
  
#Subjects Routes
  resources :subjects do
    match '/screening', :to => 'subjects#screening', :via => [:get, :post]
    match '/comment', :to => 'subjects#comment', :via => [:get, :post]
  end

  match '/screening_view', :to => 'subjects#screening_view', :via => [:get, :post]
  match '/newsubject', :to => 'subjects#new', :via => [:get, :post]
  match '/randomize', :to => 'subjects#randomize', :via => [:get, :post]
  match '/screening_log', :to => 'subjects#screening_log', :via => [:get, :post]
  match '/screening_crf_data', :to => 'subjects#screening_crf_data', :via => [:get, :post]
end

app/models/subject.rb
class Subject < ActiveRecord::Base
   include ActiveModel::Conversion
   extend ActiveModel::Naming
   self.per_page = 10000

   # Relations
   
   has_one :baseline
   has_one :treatment_completion
   has_one :follow_up3_week
   has_one :follow_up6_week
   has_one :follow_up18_week
   has_one :follow_up6_month
   has_one :follow_up1_year
   has_one :psychosocial_scale

   # Arraysreatment_completions/

   CRFS = %w[Baseline TreatmentCompletion FollowUp3Week FollowUp6Week FollowUp18Week FollowUp6Month FollowUp1Year]
 
   # Screening Variables
   # Deprecated
   # attr_accessible :subject_id, :study_site, :sc_smpsq_1, :sc_smpsq_2, :sc_smpsq_3, :sc_smpsq_4, :sc_smpsq_4a, :sc_smpsq_5, :sc_smpsq_6, :sc_smpsq_7, :sc_smpsq_8, :sc_smpsq_9, :sc_smpsq_10
   # attr_accessible :sc_inc_1, :sc_inc_2, :sc_inc_2a, :sc_inc_2b, :sc_inc_3, :sc_inc_4, :sc_inc_5, :sc_exc_1, :sc_exc_2, :sc_exc_3, :sc_exc_4, :sc_pd_1, :sc_pd_2, :sc_pd_3, :sc_pd_4, :sc_pd_4o, :sc_pd_5, :sc_pd_6, :sc_pe_1, :sc_pe_2, :sc_pe_3, :sc_pe_4, :sc_pe_4a, :sc_pe_5, :sc_pe_5o, :sc_pe_5o_reason, :sc_ic_1, :sc_ic_2, :sc_ic_3, :sc_ic_4, :sc_ic_5
   # attr_accessible :enrolled, :reason_not_enrolled, :reason_not_enrolled_other
   # attr_accessible :screening_id, :telehealth, :sc_pe_3a, :treatment_group

   # Comments
   # attr_accessible :comments
   
   # Validations

   validates :screening_id, :presence => {:message => 'Screening ID cannot be blank.'}, :uniqueness => {:message => 'Screening ID already found in database.'}, :length => { is: 5 }, :format => {:with => /^S\w{4}$/i, :message => 'Format must be S####', :multiline => true}
   validates :study_site, :presence => {:message => 'Study Site cannot be blank.'}

end



#Validations for Randomization
# validates_presence_of :group_size_input, :site_input, :group_name, :presence => true, :on => :update
# validates_numericality_of :group_size_input, :site_input
# validates :group_size_input, inclusion: { in: 6..10,
#    message: "Please enter a group size between 6 and 10"
# }

# Validations for new subject

# Variables for Randomization

# attr_accessible :group_size_input, :site_input, :group_name, :screening_id, :telehealth, :sc_pe_3a
# attr_accessor :test_rand_variable, :treatment

# validates :subject_id, :uniqueness => {:message => "Subject ID already found in database."}, :length => { is: 4, :message => 'Subject ID must be 4 numbers long' }
# validates :enrolled, :presence => {:message => 'Enrolled cannot be blank.'}

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  before_action :authenticate_user!


  def index
    @subjects = Subject.paginate(page: params[:page])

    # Used to produce table links
    @crf_to_view = [Baseline, FollowUp3Week, TreatmentCompletion, FollowUp18Week, FollowUp6Month, PsychosocialScale]
  end

  def new
    @subject = Subject.new
  end
  
  def show
    @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(params[:subject].permit(:study_site, :screening_id))
    respond_to do |format|
      if @subject.save
        create_crf_records(@subject)
        flash[:success] = "Subject successfully added."
        format.html { render action: "screening" }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])

    # if @subject.update_attributes(params[:subject].permit(:subject_screening_log_params))
    if @subject.update_attributes!(subject_params)

      create_crf_records(@subject)
      flash[:success] = "Subject Screening Log Updated"
      redirect_to screening_log_path
    else
      flash[:failure] = "Subject Screening was NOT updated. Error occurred."

      format.json { render json: @subject.errors, status: :unprocessable_entity }
      redirect_to subjects_url
    end
  end

  def destroy
    if current_user.is? :admin
      @subject = Subject.find(params[:id])
      @baseline = Baseline.find(params[:id])
      @week3 = FollowUp3Week.find(params[:id])
      @week6 = FollowUp6Week.find(params[:id])
      @tc = TreatmentCompletion.find(params[:id])
      @week18 = FollowUp18Week.find(params[:id])
      @year1 = FollowUp1Year.find(params[:id])

      # Uncomment to allow the Delete subject button to work
      # @subject.destroy
      # @baseline.destroy
      # @week3.destroy
      # @week6.destroy
      # @tc.destroy
      # @week18.destroy
      # @year1.destroy

      respond_to do |format|
        format.html { redirect_to subjects_path }
        format.json { head :no_content }
      end
    end
  end

  def screening_log
    @subjects = Subject.paginate(page: params[:page])
  end

  def screening_view
    @subjects = Subject.paginate(page: params[:page])
  end

  def screening_crf_data
    @subjects = Subject.paginate(page: params[:page])
  end


  def screening
    @subject = Subject.find(params[:subject_id])
  end

  def comment
    @subjects = Subject.find(params[:subject_id])

    if params[:submit_button]
      @subjects.update_attributes!(comment_params)
      redirect_to subjects_path
    end
  end


private 

  CRF_TO_CREATE = [Baseline, TreatmentCompletion, FollowUp3Week, FollowUp6Week, FollowUp18Week, FollowUp6Month, FollowUp1Year, PsychosocialScale]

  # Task: Refactor params out into individual blocks, for extra security
  # def subject_screening_log_params
  #   params.require(:subject).permit(:subject_id, :enrolled)
  # end
  def comment_params
    params.require(:subjects).permit(:treatment_group, :comments)
  end
  def subject_params
    params.require(:subject).permit(:comments, :screening_id, :telehealth, :sc_pe_3a, :treatment_group, :enrolled, :reason_not_enrolled, :reason_not_enrolled_other, :sc_inc_1, :sc_inc_2, :sc_inc_2a, :sc_inc_2b, :sc_inc_3, :sc_inc_4, :sc_inc_5, :sc_exc_1, :sc_exc_2, :sc_exc_3, :sc_exc_4, :sc_pd_1, :sc_pd_2, :sc_pd_3, :sc_pd_4, :sc_pd_4o, :sc_pd_5, :sc_pd_6, :sc_pe_1, :sc_pe_2, :sc_pe_3, :sc_pe_4, :sc_pe_4a, :sc_pe_5, :sc_pe_5o, :sc_pe_5o_reason, :sc_ic_1, :sc_ic_2, :sc_ic_3, :sc_ic_4, :sc_ic_5, :subject_id, :study_site, :sc_smpsq_1, :sc_smpsq_2, :sc_smpsq_3, :sc_smpsq_4, :sc_smpsq_4a, :sc_smpsq_5, :sc_smpsq_6, :sc_smpsq_7, :sc_smpsq_8, :sc_smpsq_9, :sc_smpsq_10)
  end

  # Create all CRF records once a screened subject becomes enrolled and has been assigned a subject ID
  def create_crf_records(sub)

    if sub.subject_id != nil and sub.enrolled == 1
       CRF_TO_CREATE.each do |crf|
          if crf.exists?(subject_id: sub.subject_id)
             #do nothing
          else
             crf.create(subject_id: sub.subject_id)
          end
       end   
    end
  end
    
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<div style="width:300px;margin:auto;">
<%= form_for(@subject) do |f| %>
  <!-- Look for errors -->
  <% if @subject.errors.any? %>
    <div id="error_explanation"></div>
      <h2>
        <%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:
      </h2>
      <ul>
        <% @subject.errors.messages.values.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Add new subject to Subject -->
    <p>Study Site:</p>
    <% if current_user.user_study_site == 1 %>
      <%= f.select :study_site, [["Seattle", 1]] %>
    
    <% elsif current_user.user_study_site == 2 %>
      <%= f.select :study_site, [["Houston", 2]] %>
   
    <% elsif current_user.user_study_site == 3 %>
      <%= f.select :study_site, [["Cleveland", 3]] %>
    
    <% elsif current_user.user_study_site == 4 %>
      <%= f.select :study_site, [["Tampa", 4]] %>
    <% elsif current_user.user_study_site == 5 %>
      <%= f.select :study_site, [["Minneapolis", 5]] %>
    <% elsif current_user.is? :admin %>
      <%= f.select :study_site, [["Seattle", 1],["Houston", 2],["Cleveland", 3],["Tampa", 4],["Minneapolis", 5]] %>
    <% end %>
    <p>Screening ID Number:</p>
    <%= f.text_field :screening_id, :value => "S" %>

    <%= f.submit "Save Participant", class: "btn btn-large btn-primary" %>
<% end %> 
</div>

app/views/subjects/create.html.erb
<h1>Subjects#create</h1>
<p>Find me in app/views/subjects/create.html.erb</p>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

  <h2>Screening ID: <%= @subject.screening_id %></h2>
<div class="row">
	<div class="span6 offset3">
		<div style="width:300px;margin:auto;">
				<%= render 'edit_form' %>
		</div>
	</div>
</div>

app/views/subjects/index.html.erb
<h1>Participant Data Entry</h1>
<p>With this table, you can view all currently entered subjects and quickly view or search for any table element. This table automatically sorts itself as you do so. For this particular table, try searching for a Participant ID.</p>
<br />
<div class="screeing_log_table">
  <table id="all_participant_table" cellpadding="0" cellspacing="0" border="0" class="table table-bordered">
    <thead>
      <tr>
        <th>Comments</th>
        <th>Subject ID</th>
        <th>Study Site</th>
        <th>Baseline</th>
        <th>3 Week Chart Review</th>
        <th>Treatment Completion</th>
        <th>18 Week Chart Review</th>
        <th>6 Month Follow Up</th>
        <th>PTCS – Facilitator only</th>
        <th>1 Year Questionnaire</th>
        <% if current_user.is? :admin %>
          <th>Delete</th>
        <% end %>
      </tr>
    </thead> 
    <body>
      <% @subjects.each do |sub| %>
      <% if (current_user.user_study_site == sub.study_site) or current_user.is? :admin and sub.subject_id != nil %>
        <tr>
          <% if Subject.where(subject_id: sub.subject_id).first != nil %>
            <td><%= link_to "edit", subject_comment_path(Subject.where(subject_id: sub.subject_id).first) %></td>
          <% else %>
            <td><%= Subject.create(subject_id: sub.subject_id) %></td>
          <% end %>

          <td><%= sub.subject_id %></td>
          <td><%= sub.study_site == 1? "Seattle" : sub.study_site == 2? "Houston" : sub.study_site == 3? "Cleveland" : sub.study_site == 4? "Tampa" : sub.study_site == 5? "Minneapolis" : "nil"%></td>
   

<!-- All CRF -->
          <% if Baseline.where(subject_id: sub.subject_id).first != nil %> 
              <% if Baseline.where(subject_id: sub.subject_id).first.baseline_crf_status == 1 %> 
                <td bgcolor="#98FB98" >
              <% elsif Baseline.where(subject_id: sub.subject_id).first.baseline_crf_status == 2 %>
                <td bgcolor="#befcb0" >
              <% elsif Baseline.where(subject_id: sub.subject_id).first.baseline_crf_status == 3 %>
                <td bgcolor="#818480" >
              <% elsif Baseline.where(subject_id: sub.subject_id).first.baseline_crf_status == 6 %>
                <td bgcolor="#000000" >
              <% elsif Baseline.where(subject_id: sub.subject_id).first.baseline_crf_status == 8 %>
                <td bgcolor="#FF9933" >
              <% else %>
                <td>
              <% end %>          
            <%= link_to "edit", baseline_path(Baseline.where(subject_id: sub.subject_id).first) %>    
          <% else %>
                <td>
            <%= Baseline.create(subject_id: sub.subject_id) %>
          <% end %> 
                </td>

          <% if FollowUp3Week.where(subject_id: sub.subject_id).first != nil %>
            <% if FollowUp3Week.where(subject_id: sub.subject_id).first.fu3week_crf_status == 1 %> 
              <td bgcolor="#98FB98" >
            <% elsif FollowUp3Week.where(subject_id: sub.subject_id).first.fu3week_crf_status == 2 %>
              <td bgcolor="#befcb0" >
            <% elsif FollowUp3Week.where(subject_id: sub.subject_id).first.fu3week_crf_status == 3 %>
              <td bgcolor="#818480" >
            <% elsif FollowUp3Week.where(subject_id: sub.subject_id).first.fu3week_crf_status == 6 %>
                <td bgcolor="#000000" >
            <% elsif FollowUp3Week.where(subject_id: sub.subject_id).first.fu3week_crf_status == 8 %>
                <td bgcolor="#FF9933" >
            <% else %>
              <td>
            <% end %>
          <%= link_to "edit", follow_up3_week_path(FollowUp3Week.where(subject_id: sub.subject_id).first) %>
         <% else %>
               <td>
            <% FollowUp3Week.create(subject_id: sub.subject_id) %>
         <% end %>
              </td>

         <% if TreatmentCompletion.where(subject_id: sub.subject_id).first != nil %>
            <% if TreatmentCompletion.where(subject_id: sub.subject_id).first.tc_crf_status == 1 %> 
              <td bgcolor="#98FB98" >
            <% elsif TreatmentCompletion.where(subject_id: sub.subject_id).first.tc_crf_status == 2 %>
                <td bgcolor="#befcb0" >
            <% elsif TreatmentCompletion.where(subject_id: sub.subject_id).first.tc_crf_status == 3 %>
                <td bgcolor="#818480" >
            <% elsif TreatmentCompletion.where(subject_id: sub.subject_id).first.tc_crf_status == 6 %>
                <td bgcolor="#000000" >
            <% elsif TreatmentCompletion.where(subject_id: sub.subject_id).first.tc_crf_status == 8 %>
                <td bgcolor="#FF9933" >
            <% else %>
              <td>
            <% end %>
          <%= link_to "edit", treatment_completion_path(TreatmentCompletion.where(subject_id: sub.subject_id).first) %>
        <% else %>
              <td>
          <% TreatmentCompletion.create(subject_id: sub.subject_id) %>
        <% end %>
              </td>
        
         <% if FollowUp18Week.where(subject_id: sub.subject_id).first != nil %>
              <% if FollowUp18Week.where(subject_id: sub.subject_id).first.fu18week_crf_status == 1 %> 
                <td bgcolor="#98FB98" >
              <% elsif FollowUp18Week.where(subject_id: sub.subject_id).first.fu18week_crf_status == 2 %>
                <td bgcolor="#befcb0" >
              <% elsif FollowUp18Week.where(subject_id: sub.subject_id).first.fu18week_crf_status == 3 %>
                <td bgcolor="#818480" >
              <% elsif FollowUp18Week.where(subject_id: sub.subject_id).first.fu18week_crf_status == 6 %>
                <td bgcolor="#000000" >
              <% elsif FollowUp18Week.where(subject_id: sub.subject_id).first.fu18week_crf_status == 8 %>
                <td bgcolor="#FF9933" >
              <% else %>
                <td>
              <% end %>
            <%= link_to "edit", follow_up18_week_path(FollowUp18Week.where(subject_id: sub.subject_id).first) %>
         <% else %>
                <td>
            <% FollowUp18Week.create(subject_id: sub.subject_id) %>
         <% end %>
                </td>

         <% if FollowUp6Month.where(subject_id: sub.subject_id).first != nil %>
              <% if FollowUp6Month.where(subject_id: sub.subject_id).first.fu6month_crf_status == 1 %> 
                <td bgcolor="#98FB98" >
              <% elsif FollowUp6Month.where(subject_id: sub.subject_id).first.fu6month_crf_status == 2 %>
                <td bgcolor="#befcb0" >
              <% elsif FollowUp6Month.where(subject_id: sub.subject_id).first.fu6month_crf_status == 3 %>
                <td bgcolor="#818480" >
              <% elsif FollowUp6Month.where(subject_id: sub.subject_id).first.fu6month_crf_status == 6 %>
                <td bgcolor="#000000" >
              <% elsif FollowUp6Month.where(subject_id: sub.subject_id).first.fu6month_crf_status == 8 %>
                <td bgcolor="#FF9933" >
              <% else %>
                <td>
              <% end %>
            <%= link_to "edit", follow_up6_month_path(FollowUp6Month.where(subject_id: sub.subject_id).first) %>
         <% else %>
                <td>
            <% FollowUp6Month.create(subject_id: sub.subject_id) %>
         <% end %>
               </td>

          <td>
            <% if PsychosocialScale.where(subject_id: sub.subject_id).first != nil %>
              <%= link_to "edit", psychosocial_scale_path(PsychosocialScale.where(subject_id: sub.subject_id).first) %>
            <% else %>
              <% PsychosocialScale.create(subject_id: sub.subject_id) %>
            <% end %>
          </td>

          <% if FollowUp1Year.where(subject_id: sub.subject_id).first != nil %>
              <% if FollowUp1Year.where(subject_id: sub.subject_id).first.fu1year_crf_status == 1 %> 
                <td bgcolor="#98FB98" >
              <% elsif FollowUp1Year.where(subject_id: sub.subject_id).first.fu1year_crf_status == 2 %>
                <td bgcolor="#befcb0" >
              <% elsif FollowUp1Year.where(subject_id: sub.subject_id).first.fu1year_crf_status == 3 %>
                <td bgcolor="#818480" >
              <% elsif FollowUp1Year.where(subject_id: sub.subject_id).first.fu1year_crf_status == 6 %>
                <td bgcolor="#000000" >
              <% elsif FollowUp1Year.where(subject_id: sub.subject_id).first.fu1year_crf_status == 8 %>
                <td bgcolor="#FF9933" >
              <% else %>
                <td>
              <% end %>
            <%= link_to "edit", follow_up1_year_path(FollowUp1Year.where(subject_id: sub.subject_id).first) %>
          <% else %>
                <td>
              <% FollowUp1Year.create(subject_id: sub.subject_id) %>
          <% end %>
                </td>
   
          <% if current_user.is? :admin %>
            <td>
              <%= link_to "delete", sub, method: :delete, confirm: "Delete subject?" %>
            </td>
          <% end %>
        </tr>
        <% end %> 
      <% end %>
    </body>
  </table>
</div>

app/views/subjects/new.html.erb
<h1>New subject</h1>
<div class="row">
	<div class="span6 offset3">
		<div class="span6 offset3" style="width:300px; margin:auto;">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/subjects/screening_log.html.erb
<h1>Screening Log</h1>
<p>View the complete screening log here.</p>
<br />
<div class="screening_log_table">
  <table id="screening_log" cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Screening ID</th>
        <th>Subject ID</th>
        <th>Study Site</th>
        <th>Eligible</th>
        <th>Reason Not Eligible</th>
        <th>Enrolled</th>
        <th>Reason Not Enrolled</th>
        <% if current_user.is? :admin %>
          <th>Randomized</th>
        <% end %>
        <th>Screening CRF</th>

        <% if current_user.is? :admin %>
          <th>Delete</th>
        <% end %>


      </tr>
    </thead> 
    <tbody>
      <% @subjects.each do |sub| %>
      <% if (current_user.user_study_site == sub.study_site) or current_user.is? :admin %>
        <tr>
          <td><%= sub.screening_id %></td>
          <td><%= sub.subject_id %></td>
          <td><%= sub.study_site == 1? "Seattle" : sub.study_site == 2? "Houston" : sub.study_site == 3? "Cleveland" : sub.study_site == 4? "Tampa" : sub.study_site == 5? "Minneapolis" : "nil" %></td> 
          <td><%= sub.sc_pe_3 %></td>
          <td><%= sub.sc_pe_5 %></td>
          <td><%= sub.enrolled %></td>
          <td><%= sub.sc_pe_3a %></td>
          <% if current_user.is? :admin %>
            <td><%= sub.treatment_group %></td>
          <% end %>
          <td><%= link_to "Screening CRF", subject_screening_path(sub) %></td>
          <% if current_user.is? :admin %>
            <td>
              <%= link_to "delete", sub, method: :delete, confirm: "Delete subject?" %>
            </td>
          <% end %>
        </tr> 
        <% end %>
      <% end %>
    </tbody>
  </table>
<div>